AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    trip

    Rest API to manage a Data Lake of trips

Globals:
    Function:
        Timeout: 20
        MemorySize: 512
        Environment:
          Variables:
            TABLE_NAME: !Ref TripTable
            ENDPOINT_OVERRIDE: ""

Resources:

  CreateTripFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-0.0.1-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.CreateTripFunction::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       CreateTrip:
         Type: Api
         Properties:
           Path: /trips
           Method: post
           
  GetTripByCityFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-0.0.1-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.GetTripByCity::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       GetTripByCity:
         Type: Api
         Properties:
           Path: /trips
           Method: get
           RequestParameters:
              - method.request.querystring.city
              
  GetTripByCountryFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-0.0.1-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.GetTripByCountry::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       GetTripByCountry:
         Type: Api
         Properties:
           Path: /trips
           Method: get
           RequestParameters:
            - method.request.querystring.country

  GetTripByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-0.0.1-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.GetTripByPeriod::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable
     Events:
       GetTripByPeriodFunction:
         Type: Api
         Properties:
           Path: /trips
           Method: get
           RequestParameters:
            - method.request.querystring.starts
            - method.request.querystring.ends
              
  StudyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
        - AttributeName: country
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: reason
          AttributeType: S            
      KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      LocalSecondaryIndexes: 
        - IndexName: cityIndex
          KeySchema: 
            - AttributeName: country
              KeyType: HASH
            - AttributeName: city
              KeyType: RANGE
          Projection:
             ProjectionType: ALL      
      BillingMode: PAY_PER_REQUEST              

Outputs:

    CreateTripFunction:
      Description: "CreateTrip Lambda Function ARN"
      Value: !GetAtt CreateTripFunction.Arn
      
    GetTripByCityFunction:
      Description: "GetTripByCity Lambda Function ARN"
      Value: !GetAtt GetTripByCityFunction.Arn
      
    GetTripByCountryFunction:
      Description: "GetTripByCountry Lambda Function ARN"
      Value: !GetAtt GetTripByCountryFunction.Arn
      
    GetTripByPeriodFunction:
      Description: "GetTripByPeriod Lambda Function ARN"
      Value: !GetAtt GetTripByPeriodFunction.Arn