AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    trip-aws

    Rest API to manage a Data Lake of trips

Globals:
    Function:
        Timeout: 200
        MemorySize: 512
        Environment:
          Variables:
            TABLE_NAME: !Ref TripTable
            ENDPOINT_OVERRIDE: ""

Resources:

  CreateTripFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-0.0.1-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.fiap.trip.handler.CreateTrip::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       CreateTrip:
         Type: Api
         Properties:
           Path: /trips
           Method: post
           
  GetTripByCityFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-0.0.1-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.fiap.trip.handler.GetTripByCity::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       GetTripByCity:
         Type: Api
         Properties:
           Path: /trips/{country}/findByCity
           Method: get
           RequestParameters:
              - method.request.querystring.city
              
  GetTripByCountryFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-0.0.1-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.fiap.trip.handler.GetTripByCountry::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       GetTripByCountry:
         Type: Api
         Properties:
           Path: /trips/findByCountry
           Method: get
           RequestParameters:
            - method.request.querystring.country

  GetTripByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-0.0.1-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.fiap.trip.handler.GetTripByPeriod::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable
     Events:
       GetTripByPeriodFunction:
         Type: Api
         Properties:
           Path: /trips/findByPeriod
           Method: get
           RequestParameters:
            - method.request.querystring.starts
            - method.request.querystring.ends
              
  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH    
      BillingMode: PAY_PER_REQUEST              

Outputs:

    CreateTripFunction:
      Description: "CreateTrip Lambda Function ARN"
      Value: !GetAtt CreateTripFunction.Arn
      
    GetTripByCityFunction:
      Description: "GetTripByCity Lambda Function ARN"
      Value: !GetAtt GetTripByCityFunction.Arn
      
    GetTripByCountryFunction:
      Description: "GetTripByCountry Lambda Function ARN"
      Value: !GetAtt GetTripByCountryFunction.Arn
      
    GetTripByPeriodFunction:
      Description: "GetTripByPeriod Lambda Function ARN"
      Value: !GetAtt GetTripByPeriodFunction.Arn